Fix/soc 5487
exoplatform/platform pull request #567
Opened 2016-10-25 11:15 UTC by aboughzela

2016-10-25 11:27 UTC, boubaker requested changes

2016-10-25 11:27 UTC, boubaker commented on extension/config/src/main/resources/conf/platform/exo-sample.properties
> +# exo.activity-type.cs-calendar:spaces.enabled=true
List all activity types in comment, for example:

+# exo.activity-type.DOC_ACTIVITY.enabled=true
 +# exo.activity-type.cs-calendar:spaces.enabled=true
 +# exo.activity-type.ks-poll:spaces.enabled=true
 +# exo.activity-type.USER_ACTIVITIES_FOR_RELATIONSHIP.enabled=true
...

2016-10-25 11:27 UTC, boubaker commented on extension/config/src/main/resources/conf/platform/configuration.properties
> +exo.social.activity.types= ${exo.social.activity.types:DEFAULT_ACTIVITY,SPACE_ACTIVITY,USER_ACTIVITIES_FOR_SPACE,exosocial:relationship,LINK_ACTIVITY,sharecontents:spaces,USER_PROFILE_ACTIVITY,DOC_AC
Add 
,${exo.social.activity.custom.types}
at the end.

2016-10-25 12:10 UTC, aboughzela commented on extension/config/src/main/resources/conf/platform/configuration.properties
> +exo.social.activity.types= ${exo.social.activity.types:DEFAULT_ACTIVITY,SPACE_ACTIVITY,USER_ACTIVITIES_FOR_SPACE,exosocial:relationship,LINK_ACTIVITY,sharecontents:spaces,USER_PROFILE_ACTIVITY,DOC_AC
exo.social.activity.custom.types added in exo-sample.properties

2016-10-25 12:11 UTC, aboughzela commented on extension/config/src/main/resources/conf/platform/exo-sample.properties
> +# exo.activity-type.cs-calendar:spaces.enabled=true
Done

2016-10-25 12:54 UTC, thomasdelhomenie commented on extension/config/src/main/resources/conf/platform/configuration.properties
> +exo.social.activity.types= ${exo.social.activity.types:DEFAULT_ACTIVITY,SPACE_ACTIVITY,USER_ACTIVITIES_FOR_SPACE,exosocial:relationship,LINK_ACTIVITY,sharecontents:spaces,USER_PROFILE_ACTIVITY,DOC_AC
What is the goal of this property and what is the impact for a developer who wants to add its own custom activity type ?

2016-10-31 16:10 UTC, thomasdelhomenie approved these changes

2016-10-31 17:02 UTC, closed without merging